#!/bin/sh

line=20
record=1

echo "10 OPEN \"D\",#1,\"MODES/DAT\",32"

while read modeinfo
do
	echo "${line} WRITE #1,${modeinfo}"
	echo "$((${line} + 10)) PUT #1,${record}"
	line=$((${line} + 20))
	record=$((${record} + 1))
done < $1

echo "${line} CLOSE #1"
