#!/bin/sh

FRAMESTEP=2
SAMPLES=735

#MAXSCORE=896
MAXSCORE=768

BINDIR=$(dirname $0)

PPM2RAW=${BINDIR}/ppm2raw
RAW2DRW=${BINDIR}/raw2drw
DRW2DRL=${BINDIR}/drw2drl
DRLPRUNE=${BINDIR}/drlprune
DRL2RAW=${BINDIR}/drl2raw
WATCHOUT=${BINDIR}/watchout

PPMBASE=../ppm/"$2"
RAWBASE=../raw/"$2"
PCMBASE=../pcm/"$2"

cleanup()
{
	rm -f buildout.$$

	rm ../mov/"$2".mov
	rm ../mov/"$2".wav

	rm -rf $PPMBASE
	rm -rf $RAWBASE
	rm -rf $PCMBASE

	exit 0
}

# START HERE

trap cleanup 1 2 3 15

mkdir -p $PPMBASE
mkdir -p $RAWBASE
mkdir -p $PCMBASE

echo Transcoding $(basename "$1")...
nice -n 1 ffmpeg -i "$1" -r 30 -ar 11025 -ac 1 -b 200000 -acodec pcm_u8 \
	-f mov -y ../mov/"$2".mov
nice -n 1 ffmpeg -i ../mov/"$2".mov -vn -acodec pcm_u8 -y ../mov/"$2".wav
nice -n 1 normalize ../mov/"$2".wav

echo Converting .mov file to a sequence of .ppm files...
cd $PPMBASE
nice -n 1 ffmpeg -i ../../mov/"$2".mov %d.ppm >/dev/null 2>&1
# Not necessary to delete MOV here, but why wait?
rm ../../mov/"$2".mov
FRAMES=$(ls | wc -l)
cd - >/dev/null

echo Converting .wav file to .pcm file and split into appropriately sized chunks...
cd $PCMBASE
dd if=../../mov/"$2".wav bs=44 skip=1 | \
	nice -n 1 split -d -b $SAMPLES -a 10 - "$2".
# Not necessary to delete WAV here, but why wait?
rm ../../mov/"$2".wav
cd - >/dev/null

CURRAW=${RAWBASE}/current.raw
TMPRAW=${RAWBASE}/tmp.raw

# Start with all-black frame...
cp ${BINDIR}/BLACK.raw $CURRAW

echo Building final output file...

$WATCHOUT "$2" &

cat ${BINDIR}/BLACK.drl > "$2".out
dd if=/dev/zero bs=$SAMPLES count=1 2>/dev/null >> "$2".out

mkfifo buildout.$$

for i in $(seq 1 $FRAMESTEP $FRAMES)
do
	if [ $(($i % $((10 * 30)))) -eq 1 ]
	then
		echo Processing frame ${i}... >&2
	fi
	PPM=${PPMBASE}/$i.ppm
	DRL=${DRLBASE}/${i}.drl
	PCMFILE=${PCMBASE}/"$2".$(printf "%010d" $(($i / $FRAMESTEP)))

	$DRL2RAW $CURRAW buildout.$$ $TMPRAW &
	CURUPDATE=$!
	convert -resize 125x200%! -resize 128x192 \
			-ordered-dither o2x2,4,4,4 \
			-quantize YIQ +dither -map ${BINDIR}/colormap.ppm \
			-background black -gravity center -extent 128x192 \
			$PPM ppm:- | \
		$PPM2RAW - -|\
		$RAW2DRW $CURRAW - - | \
		$DRW2DRL - - | \
		$DRLPRUNE $CURRAW - - $MAXSCORE | \
		tee buildout.$$
	# Not necessary to delete PPM here, but why wait?
	rm $PPM
	wait $CURUPDATE
	mv $TMPRAW $CURRAW
	if [ -f $PCMFILE ]
	then
		cat $PCMFILE
		PCMSIZE=$(stat -c '%s' $PCMFILE)
		if [ $PCMSIZE -lt $SAMPLES ]
		then
			dd if=/dev/zero bs=$(($SAMPLES - $PCMSIZE)) \
				count=1 2>/dev/null
		fi
	else
		# This actually holds DAC at lowest value...
		# ...should output 0x88 ("CoCo Law" virtual zero) instead?
		dd if=/dev/zero bs=$SAMPLES count=1 2>/dev/null
	fi
done >> "$2".out

echo Done!

cleanup
