all: ppm2raw raw2rle raw2rl3 rle2raw raw2drw drw2drl drl2raw wav2pcm pcm2clw clw2pcm

ppm2raw: ppm2raw.c
	gcc -o ppm2raw ppm2raw.c

raw2rle: raw2rle.c
	gcc -o raw2rle raw2rle.c

raw2rl3: raw2rl3.c
	gcc -o raw2rl3 raw2rl3.c

rle2raw: rle2raw.c
	gcc -o rle2raw rle2raw.c

raw2drw: raw2drw.c
	gcc -o raw2drw raw2drw.c

drw2drl: drw2drl.c
	gcc -o drw2drl drw2drl.c

drl2raw: drl2raw.c
	gcc -o drl2raw drl2raw.c

wav2pcm: wav2pcm.c
	gcc -o wav2pcm wav2pcm.c

pcm2clw: pcm2clw.c
	gcc -o pcm2clw pcm2clw.c

clw2pcm: clw2pcm.c
	gcc -o clw2pcm clw2pcm.c
