#!/bin/sh

split -d -b 368 -a 10 "$1" "$2"

for i in *.000000000*; do mv $i $(echo $i | sed -e 's/000000000\(.\)$/\1/'); done
for i in *.00000000*; do mv $i $(echo $i | sed -e 's/00000000\(..\)$/\1/'); done
for i in *.0000000*; do mv $i $(echo $i | sed -e 's/0000000\(...\)$/\1/'); done
for i in *.000000*; do mv $i $(echo $i | sed -e 's/000000\(....\)$/\1/'); done
for i in *.00000*; do mv $i $(echo $i | sed -e 's/00000\(.....\)$/\1/'); done
for i in *.0000*; do mv $i $(echo $i | sed -e 's/0000\(......\)$/\1/'); done
for i in *.000*; do mv $i $(echo $i | sed -e 's/000\(.......\)$/\1/'); done
for i in *.00*; do mv $i $(echo $i | sed -e 's/00\(........\)$/\1/'); done
for i in *.0*; do mv $i $(echo $i | sed -e 's/0\(.........\)$/\1/'); done
