#!/bin/sh

#mencoder tv:// -tv driver=v4l2:norm=NTSC:device=/dev/video1:mjpeg:decimation=4:forceaudio=1:adevice=/dev/dsp2 -oac copy -ovc copy -endpos "$2" -o "$1"
mencoder tv:// -tv driver=v4l2:norm=NTSC:device=/dev/video1:mjpeg:decimation=4:forceaudio=1:alsa:adevice=hw.1,0 -oac pcm -ovc copy -endpos "$2" -o "$1"
