#!/bin/sh

if [ -z "$2" ]
then
	MODE=0
else
	MODE=$2
fi

if [ x$MODE == x0 ]
then
	RESIZE_OPTS="180x100%!"
elif [ x$MODE == x1 ]
then
	RESIZE_OPTS="90x100%!"
elif [ x$MODE == x2 ]
then
	RESIZE_OPTS="90x100%!"
elif [ x$MODE == x3 ]
then
	RESIZE_OPTS="180x100%!"
elif [ x$MODE == x4 ]
then
	RESIZE_OPTS="90x100%!"
else
	echo "Unknown video mode ${MODE}!"
	exit 1
fi

RAW2PPM=$(dirname $0)/raw2ppm${MODE}

cleanup()
{
	kill -HUP $PID >/dev/null 2>&1
	kill -HUP $OLDPID >/dev/null 2>&1
	exit 0
}

trap cleanup 1 2 3 15

FEH_ARGS='-Z -F'

while [ ! -d ../raw/$1 ]
do
	sleep 1
done

cd ../raw/$1

while [ ! -f current.raw ]
do
	sleep 1
done

LASTMOD=$(stat -c '%Y' current.raw)
$RAW2PPM current.raw current.ppm >/dev/null 2>&1
while ! convert -resize ${RESIZE_OPTS} current.ppm view.ppm >/dev/null 2>&1
do
	sleep 1
done
feh $FEH_ARGS view.ppm >/dev/null 2>&1 &
OLDPID=$!

while true
do
	if [ ! -d /proc/$OLDPID ]
	then
		break
	fi
	if [ -f current.raw ]
	then
		CURMOD=$(stat -c '%Y' current.raw)
	else
		break
	fi
	if [ $? != 0 ]
	then
		break
	fi
	if [ $LASTMOD -lt $CURMOD ]
	then
		LASTMOD=$CURMOD
		$RAW2PPM current.raw current.ppm >/dev/null 2>&1
		while ! convert -resize ${RESIZE_OPTS} current.ppm view.ppm >/dev/null 2>&1
		do
			sleep 1
		done
		feh $FEH_ARGS view.ppm >/dev/null 2>&1 &
		PID=$!
		sleep 1
		kill -HUP $OLDPID >/dev/null 2>&1
		OLDPID=$PID
	fi
done

cleanup
